I've used https://www.strerr.com/en/sqliteviewer.html#, an online sql database viewer to see all the tables clearly. And I've written all the problems I've found in the comments.

In [19]:
class Processor:
    def __init__(self):
        self.dbPathorUrl = str()

    def getdbPathorUrl(self):
        return self.dbPathorUrl
    
    def setdbPathorUrl(self, PathorUrl):
        self.dbPathorUrl = PathorUrl

class RelationalQueryProcessor(Processor):
    def __init__(self, dbPathOrUrl):
        super().__init__(dbPathOrUrl)

    def uploadData(self, path):
        pass

In [37]:
from sqlite3 import connect
from pandas import read_csv, Series, DataFrame, read_sql
import pandas as pd
pd.options.mode.chained_assignment = None


def getAllAnnotations():
    with connect("relational.db") as con: 
        query_1 = "SELECT annotation,target,body,motivation FROM annotationsId LEFT JOIN imageId ON annotationsId.imageId == imageId.imageId"
        all_annotations_query = read_sql(query_1,con)
    return all_annotations_query
getAllAnnotations()

#It's strange isn't it, why do I have to combine two tables to know something that is already there in the raw data? 
#An annotation should be composed with a target and a body, I don't think they should be separated in two tables.
#What about uploading the annotataion raw data into the database? It could be much easier in this way.

,annotation,target,body,motivation
0,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1,https://dl.ficlit.unibo.it/iiif/2/45498/full/6...,painting
1,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p2,https://dl.ficlit.unibo.it/iiif/2/45499/full/6...,painting
2,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p3,https://dl.ficlit.unibo.it/iiif/2/45500/full/6...,painting
3,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p4,https://dl.ficlit.unibo.it/iiif/2/45501/full/6...,painting
4,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p5,https://dl.ficlit.unibo.it/iiif/2/45502/full/6...,painting
...,...,...,...,...
266,https://dl.ficlit.unibo.it/iiif/2/19425/annota...,https://dl.ficlit.unibo.it/iiif/2/19425/canvas...,https://dl.ficlit.unibo.it/iiif/2/206738/full/...,painting
267,https://dl.ficlit.unibo.it/iiif/2/19425/annota...,https://dl.ficlit.unibo.it/iiif/2/19425/canvas...,https://dl.ficlit.unibo.it/iiif/2/206739/full/...,painting
268,https://dl.ficlit.unibo.it/iiif/2/19425/annota...,https://dl.ficlit.unibo.it/iiif/2/19425/canvas...,https://dl.ficlit.unibo.it/iiif/2/206740/full/...,painting
269,https://dl.ficlit.unibo.it/iiif/2/19425/annota...,https://dl.ficlit.unibo.it/iiif/2/19425/canvas...,https://dl.ficlit.unibo.it/iiif/2/206741/full/...,painting
270,https://dl.ficlit.unibo.it/iiif/2/19425/annota...,https://dl.ficlit.unibo.it/iiif/2/19425/canvas...,https://dl.ficlit.unibo.it/iiif/2/206742/full/...,painting

In [23]:
def getAllImages():
    with connect("relational.db") as con: 
        query_2 = "SELECT body FROM imageId"
        all_images_query = read_sql(query_2,con)
    return all_images_query
getAllImages()

                                                  body
0    https://dl.ficlit.unibo.it/iiif/2/45498/full/6...
1    https://dl.ficlit.unibo.it/iiif/2/45499/full/6...
2    https://dl.ficlit.unibo.it/iiif/2/45500/full/6...
3    https://dl.ficlit.unibo.it/iiif/2/45501/full/6...
4    https://dl.ficlit.unibo.it/iiif/2/45502/full/6...
..                                                 ...
266  https://dl.ficlit.unibo.it/iiif/2/206738/full/...
267  https://dl.ficlit.unibo.it/iiif/2/206739/full/...
268  https://dl.ficlit.unibo.it/iiif/2/206740/full/...
269  https://dl.ficlit.unibo.it/iiif/2/206741/full/...
270  https://dl.ficlit.unibo.it/iiif/2/206742/full/...

[271 rows x 1 columns]

In [38]:
def getAnnotationsWithBody(): #Here I'm using the first annotation as an example just to test the query. Gonna replace it with a general one later.
    with connect("relational.db") as con: 
        query_3 = "SELECT annotation,target,body,motivation FROM annotationsId LEFT JOIN imageId ON annotationsId.imageId == imageId.imageId WHERE body='https://dl.ficlit.unibo.it/iiif/2/45498/full/699,800/0/default.jpg'"
        annotations_with_body_query = read_sql(query_3,con)
    return annotations_with_body_query
getAnnotationsWithBody()

#Same problem again, this information can be queried directly from the raw data annotation.csv without these joining troubles.

,annotation,target,body,motivation
0,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1,https://dl.ficlit.unibo.it/iiif/2/45498/full/6...,painting

In [39]:
def getAnnotationsWithBodyAndTarget(): #Here I'm using the first annotation as an example just to test the query. Gonna replace it with a general one later.
    with connect("relational.db") as con:
        query_4 = "SELECT annotation,target,body,motivation FROM annotationsId LEFT JOIN imageId ON annotationsId.imageId == imageId.imageId WHERE body='https://dl.ficlit.unibo.it/iiif/2/45498/full/699,800/0/default.jpg' AND target='https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1'"
        annotations_with_body_and_target_query = read_sql(query_4,con)
    return annotations_with_body_and_target_query
getAnnotationsWithBodyAndTarget()

#Same problem

,annotation,target,body,motivation
0,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1,https://dl.ficlit.unibo.it/iiif/2/45498/full/6...,painting

In [40]:
def getAnnotationsWithTarget(): #Here I'm using the first annotation as an example just to test the query. Gonna replace it with a general one later.
    with connect("relational.db") as con:
        query_5 = "SELECT annotation,target,body,motivation FROM annotationsId LEFT JOIN imageId ON annotationsId.imageId == imageId.imageId WHERE target='https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1'"
        annotations_with_target_query = read_sql(query_5,con)
    return annotations_with_target_query
getAnnotationsWithTarget()

#Still the same problem

,annotation,target,body,motivation
0,https://dl.ficlit.unibo.it/iiif/2/28429/annota...,https://dl.ficlit.unibo.it/iiif/2/28429/canvas/p1,https://dl.ficlit.unibo.it/iiif/2/45498/full/6...,painting

In [47]:
def getEntitiesWithCreator(): #Here I'm using John Doe as an example just to test the query. Gonna replace it with a general one later.
    with connect("relational.db") as con:
        query_6 = "SELECT id,title,creator FROM metadataId LEFT JOIN creatorsId ON metadataId.creatorId == creatorsId.creatorId WHERE creator= 'Doe, John'"
        entities_with_creator_query = read_sql(query_6,con)
    return entities_with_creator_query
getEntitiesWithCreator()

#It seems really user-unfriendly that the input has to be "Doe, John" exactly. 
#I think we could make it more user-friendly by creating table containing the first name and the last name separately, so it will be possible to query with a partial name without a format.
#But is that neccesary?
#And here's an obvious problem, in the creator column there's only John which is wrong.

,id,title,creator
0,https://dl.ficlit.unibo.it/iiif/28429/collection,Dante Alighieri: Opere,"Doe, John"

In [49]:
def getEntitiesWithTitle(): #Here I'm using Canzoniere as an example just to test the query. Gonna replace it with a general one later.
    with connect("relational.db") as con:
        query_7 = "SELECT id,title,creator FROM metadataId LEFT JOIN creatorsId ON metadataId.creatorId == creatorsId.creatorId WHERE title= 'Il Canzoniere'"
        entities_with_title_query = read_sql(query_7,con)
    return entities_with_title_query
getEntitiesWithTitle()

#Same usability problem as above. But I guess it's not our responsibility to fix it.

,id,title,creator
0,https://dl.ficlit.unibo.it/iiif/2/28429/manifest,Il Canzoniere,"Alighieri, Dante"